import blade as bld
b = bld.Blade('Sandia Blade', 'Sandia_blade.csv')

# create all the blade stations
b.stn1 = b.create_station(1)
b.stn2 = b.create_station(2)
b.stn3 = b.create_station(3)
b.stn4 = b.create_station(4)
b.stn5 = b.create_station(5)
b.stn6 = b.create_station(6)
b.stn7 = b.create_station(7)
b.stn8 = b.create_station(8)
b.stn9 = b.create_station(9)
b.stn10 = b.create_station(10)
b.stn11 = b.create_station(11)
b.stn12 = b.create_station(12)
b.stn13 = b.create_station(13)
b.stn14 = b.create_station(14)
b.stn15 = b.create_station(15)
b.stn16 = b.create_station(16)
b.stn17 = b.create_station(17)
b.stn18 = b.create_station(18)
b.stn19 = b.create_station(19)
b.stn20 = b.create_station(20)
b.stn21 = b.create_station(21)
b.stn22 = b.create_station(22)
b.stn23 = b.create_station(23)
b.stn24 = b.create_station(24)
b.stn25 = b.create_station(25)
b.stn26 = b.create_station(26)
b.stn27 = b.create_station(27)
b.stn28 = b.create_station(28)
b.stn29 = b.create_station(29)
b.stn30 = b.create_station(30)
b.stn31 = b.create_station(31)
b.stn32 = b.create_station(32)
b.stn33 = b.create_station(33)
b.stn34 = b.create_station(34)

# make some plots of the chord and twist schedules
b.plot_chord_schedule()
b.plot_twist_schedule()